# Generated by Django 5.0.6 on 2024-06-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_cartitem_cart_remove_cartitem_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subgroup',
            name='slug',
        ),
    ]
